// import { GalleryPhoto } from '@common/interfaces/gallery-photo';

// export const galleryPhotos: GalleryPhoto[] = [
//     {
//         image: 'Atelier Interne/PHOTO-2023-06-28-15-01-24.jpg',
//         date: '2023-06-28',
//         eventName: 'Atelier Interne',
//         description: 'Discussion entre collaborateurs lors de l’atelier interne.',
//     },
//     {
//         image: 'Atelier Interne/PHOTO-2023-06-28-15-01-33.jpg',
//         date: '2023-06-28',
//         eventName: 'Atelier Interne',
//         description: 'Échange entre participants sur les axes de travail.',
//     },
//     {
//         image: 'Cérémonie de lancement de la Fondation/DSC08677.jpg',
//         date: '2023-07-01',
//         eventName: 'Cérémonie de lancement de la Fondation',
//         description: 'Intervention d’un membre fondateur devant l’audience.',
//     },
//     {
//         image: 'Cérémonie de lancement de la Fondation/DSC08691.jpg',
//         date: '2023-07-01',
//         eventName: 'Cérémonie de lancement de la Fondation',
//         description: 'Moment de convivialité entre les invités.',
//     },
//     {
//         image: 'Cérémonie de lancement de la Fondation/DSC08694.jpg',
//         date: '2023-07-01',
//         eventName: 'Cérémonie de lancement de la Fondation',
//         description: 'Échanges sur la mission de la Fondation.',
//     },
//     {
//         image: 'Cérémonie de lancement de la Fondation/DSC08697.jpg',
//         date: '2023-07-01',
//         eventName: 'Cérémonie de lancement de la Fondation',
//         description: 'Allocution du président de la Fondation.',
//     },
//     {
//         image: 'Cérémonie de lancement de la Fondation/DSC08699.jpg',
//         date: '2023-07-01',
//         eventName: 'Cérémonie de lancement de la Fondation',
//         description: 'Présentation des objectifs de la Fondation.',
//     },
//     {
//         image: 'Cérémonie de lancement de la Fondation/DSC08717.jpg',
//         date: '2023-07-01',
//         eventName: 'Cérémonie de lancement de la Fondation',
//         description: 'Discours devant les partenaires institutionnels.',
//     },
//     {
//         image: 'Cérémonie de lancement de la Fondation/DSC08722.jpg',
//         date: '2023-07-01',
//         eventName: 'Cérémonie de lancement de la Fondation',
//         description: 'Participants écoutant attentivement les interventions.',
//     },
//     {
//         image: 'Cérémonie de lancement de la Fondation/DSC08723.jpg',
//         date: '2023-07-01',
//         eventName: 'Cérémonie de lancement de la Fondation',
//         description: 'Remise symbolique d’un document fondateur.',
//     },
//     {
//         image: 'Cérémonie de lancement de la Fondation/ensemble.jpg',
//         date: '2023-07-01',
//         eventName: 'Cérémonie de lancement de la Fondation',
//         description: 'Photo de groupe avec les invités et partenaires.',
//     },
//     {
//         image: 'Cérémonie de lancement de la Fondation/fgf.jpg',
//         date: '2023-07-01',
//         eventName: 'Cérémonie de lancement de la Fondation',
//         description: 'Présentation informelle entre les participants.',
//     },
//     {
//         image: 'Cérémonie de lancement de la Fondation/gh.jpg',
//         date: '2023-07-01',
//         eventName: 'Cérémonie de lancement de la Fondation',
//         description: 'Moment d’échange en comité restreint.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-09.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Préparation du tournage avec les intervenants.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-10.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Échange avec une enseignante invitée.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-11.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Arrivée des invités à l’enregistrement.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-13.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Affiche de présentation de l’émission.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-15.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Portrait d’un invité dans les coulisses.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-16.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Vue du plateau de tournage avant enregistrement.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-16 (1).jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Portrait d’une participante de l’émission.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-17.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Rencontre entre deux intervenants.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-17 (1).jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Moment de préparation en loge.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-19.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Intervenant révisant ses notes.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-24.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Portrait d’une intervenante en plateau.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-28.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Discussion en groupe sur le plateau.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-31.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Débat entre les invités de l’émission.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-32.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Présentation des partenaires de l’émission.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-32 (1).jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Interview d’un intervenant clé.',
//     },
//     {
//         image: 'Tournage emission Mon Enseignant Mon Héros/PHOTO-2025-03-20-19-43-32.jpg',
//         date: '2025-03-20',
//         eventName: "Tournage de l'émission Mon Enseignant Mon Héros",
//         description: 'Moment final du tournage.',
//     },
// ];
